name: jupyterlab-ros
channels:
- conda-forge
- robostack
- khalilahmed724/label/khalilahmed724
- conda-forge
dependencies:
- python=3.8
- nodejs=14
- jupyterlab=3.1
- ipympl
- ipyvuetify
- bqplot
- ipywidgets
- voila
- ros-noetic-ros-core
- ros-noetic-rospy
- ros-noetic-rosbridge-suite
- ros-noetic-rosbag
- ros-noetic-rosauth
- ros-noetic-tf2-web-republisher
- ros-noetic-franka-ros
- ros-noetic-interactive-marker-tutorials
- ros-noetic-teb-local-planner
- ros-noetic-turtlebot3
- ros-noetic-turtlebot3-fake
- ros-noetic-robm
- ros-noetic-myrobo
- tensorflow
- opencv
- libopencv
- py-opencv
- ros-noetic-video-stream-opencv
- ros-noetic-moveit-msgs
- ros-noetic-moveit-core
- ros-noetic-moveit-ros-planning
- ros-noetic-moveit-ros-move-group
- ros-noetic-moveit-ros-manipulation
- ros-noetic-moveit-planners-ompl
- ros-noetic-moveit-simple-controller-manager
- ros-noetic-moveit-commander
- ros-noetic-moveit-ros-control-interface
- ros-noetic-moveit-setup-assistant
- ros-noetic-moveit-plugins
- ros-noetic-moveit-ros
- ros-noetic-moveit-planners
- ros-noetic-moveit-python
- ros-noetic-moveit-visual-tools
- pyserial
- ffmpeg
# our stuff
- robostack::jupyterlab-ros
- robostack::jupyter-amphion
# - robostack::jupyter-ros=0.5
